#!/bin/bash -login
#PBS -l walltime=7:00:00
#PBS -l mem=4096mb
#PBS -N all_rewarded
#PBS -t 1-5
#PBS -M haslunjo@msu.edu

cd ~/complex_features_experiment  #where to run avida program from
mkdir results/all_rewarded/${PBS_ARRAYID}  #makes a new directory for each replicates result to be stored
cp configs/* results/all_rewarded/${PBS_ARRAYID} #copy everything in configs to different directory

cd results/all_rewarded/${PBS_ARRAYID}
./avida -set RANDOM_SEED ${PBS_ARRAYID}  

